---
sudo: false
language: node_js
notifications:
  email: false
node_js:
  - stable
  - "11"
  - "10"
cache:
  directories:
    - node_modules
before_script:
  - createdb test
services:
  - postgresql
